endpoints:
  targetHost: "155.198.198.11"
  targetPort: "30002"
  dimmerAdminHost: "155.198.198.11"
  dimmerAdminPort: "30003"
dimmableComponentPaths:
  - "recommender"
  - "news"
  - "cart"
loadGenerator:
  driver: "k6"
  k6:
    host: "localhost"
    port: "6565"
loadProfile:
  numIterations: 300
  maxUsers: 300
  rampUpSeconds: 10
  peakSeconds: 50
  rampDownSeconds: 10
  secondsBetweenRuns: 10
extensions:
  sockShopCartReseeding:
    enabled: true
    host: "155.198.198.11"
    port: "30004"
    numReseedRows: 200000
